#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AttendaceTrackingService
{
    using DbLinq.Vendor;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using DbLinq;
    using System.Linq;
    using System.Linq.Expressions;
    using System.Reflection;
    using DbLinq.Data.Linq;
    using DbLinq.Data.Linq.Mapping;
    using System.Data.Linq.Mapping;
    using MySql.Data.MySqlClient;
    using System.Configuration;
    using System.Data;

    public partial class AttendanceTrackingDBDataContext : DataContext
    {

        //private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
        private static DbLinq.Data.Linq.Mapping.AttributeMappingSource mappingSource = new DbLinq.Data.Linq.Mapping.AttributeMappingSource();

        #region Extensibility Method Definitions
        partial void OnCreated();
        partial void Insertattendance(attendance instance);
        partial void Updateattendance(attendance instance);
        partial void Deleteattendance(attendance instance);
        partial void Insertenrollment(enrollment instance);
        partial void Updateenrollment(enrollment instance);
        partial void Deleteenrollment(enrollment instance);
        partial void Insertsection(section instance);
        partial void Updatesection(section instance);
        partial void Deletesection(section instance);
        partial void Insertstudent(student instance);
        partial void Updatestudent(student instance);
        partial void Deletestudent(student instance);
        #endregion

        public AttendanceTrackingDBDataContext()
            : base(new MySqlConnection(ConfigurationManager.ConnectionStrings["connectionstring"].ConnectionString), new DbLinq.MySql.MySqlVendor())
        {
            //OnCreated();
        }

        public AttendanceTrackingDBDataContext(IDbConnection connection, IVendor vendor)
            : base(connection, vendor)
        {
        }

        public AttendanceTrackingDBDataContext(string connection) :
            base(connection, mappingSource)
        {
            //OnCreated();
        }

        public AttendanceTrackingDBDataContext(IDbConnection connection) :
            base(connection, mappingSource)
        {
            //OnCreated();
        }

        public AttendanceTrackingDBDataContext(string connection, DbLinq.Data.Linq.Mapping.AttributeMappingSource mappingSource) :
            base(connection, mappingSource)
        {
            OnCreated();
        }

        public AttendanceTrackingDBDataContext(System.Data.IDbConnection connection, DbLinq.Data.Linq.Mapping.AttributeMappingSource mappingSource) :
            base(connection, mappingSource)
        {
            OnCreated();
        }

        public Table<attendance> attendances
        {
            get
            {
                return this.GetTable<attendance>();
            }
        }

        public Table<enrollment> enrollments
        {
            get
            {
                return this.GetTable<enrollment>();
            }
        }

        public Table<section> sections
        {
            get
            {
                return this.GetTable<section>();
            }
        }

        public Table<student> students
        {
            get
            {
                return this.GetTable<student>();
            }
        }
    }

    [Table(Name = "ats_prod.attendances")]
    public partial class attendance : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _id;

        private string _student_id;

        private string _call_number;

        private string _code;

        private System.DateTime _created_at;

        private System.Nullable<System.DateTime> _updated_at;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnidChanging(int value);
        partial void OnidChanged();
        partial void Onstudent_idChanging(string value);
        partial void Onstudent_idChanged();
        partial void Oncall_numberChanging(string value);
        partial void Oncall_numberChanged();
        partial void OncodeChanging(string value);
        partial void OncodeChanged();
        partial void Oncreated_atChanging(System.Nullable<System.DateTime> value);
        partial void Oncreated_atChanged();
        partial void Onupdated_atChanging(System.Nullable<System.DateTime> value);
        partial void Onupdated_atChanged();
        #endregion

        public attendance()
        {
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    this.OnidChanging(value);
                    this.SendPropertyChanging();
                    this._id = value;
                    this.SendPropertyChanged("id");
                    this.OnidChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_student_id", DbType = "NVarChar(255)")]
        public string student_id
        {
            get
            {
                return this._student_id;
            }
            set
            {
                if ((this._student_id != value))
                {
                    this.Onstudent_idChanging(value);
                    this.SendPropertyChanging();
                    this._student_id = value;
                    this.SendPropertyChanged("student_id");
                    this.Onstudent_idChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_call_number", DbType = "NVarChar(255)")]
        public string call_number
        {
            get
            {
                return this._call_number;
            }
            set
            {
                if ((this._call_number != value))
                {
                    this.Oncall_numberChanging(value);
                    this.SendPropertyChanging();
                    this._call_number = value;
                    this.SendPropertyChanged("call_number");
                    this.Oncall_numberChanged();
                }
            }
        }


        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_code", DbType = "NVarChar(255)")]
        public string code
        {
            get
            {
                return this._code;
            }
            set
            {
                if ((this._code != value))
                {
                    this.OncodeChanging(value);
                    this.SendPropertyChanging();
                    this._code = value;
                    this.SendPropertyChanged("code");
                    this.OncodeChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_created_at", DbType = "DateTime NOT NULL")]
        public System.DateTime created_at
        {
            get
            {
                return this._created_at;
            }
            set
            {
                if ((this._created_at != value))
                {
                    this.Oncreated_atChanging(value);
                    this.SendPropertyChanging();
                    this._created_at = value;
                    this.SendPropertyChanged("created_at");
                    this.Oncreated_atChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_updated_at", DbType = "DateTime")]
        public System.Nullable<System.DateTime> updated_at
        {
            get
            {
                return this._updated_at;
            }
            set
            {
                if ((this._updated_at != value))
                {
                    this.Onupdated_atChanging(value);
                    this.SendPropertyChanging();
                    this._updated_at = value;
                    this.SendPropertyChanged("updated_at");
                    this.Onupdated_atChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [Table(Name = "ats_prod.enrollments")]
    public partial class enrollment : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _id;

        private string _student_id;

        private string _call_number;

        private System.Nullable<System.DateTime> _created_at;

        private System.Nullable<System.DateTime> _updated_at;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnidChanging(int value);
        partial void OnidChanged();
        partial void Onstudent_idChanging(string value);
        partial void Onstudent_idChanged();
        partial void Oncall_numberChanging(string value);
        partial void Oncall_numberChanged();
        partial void Oncreated_atChanging(System.Nullable<System.DateTime> value);
        partial void Oncreated_atChanged();
        partial void Onupdated_atChanging(System.Nullable<System.DateTime> value);
        partial void Onupdated_atChanged();
        #endregion

        public enrollment()
        {
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    this.OnidChanging(value);
                    this.SendPropertyChanging();
                    this._id = value;
                    this.SendPropertyChanged("id");
                    this.OnidChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_student_id", DbType = "NVarChar(255)")]
        public string student_id
        {
            get
            {
                return this._student_id;
            }
            set
            {
                if ((this._student_id != value))
                {
                    this.Onstudent_idChanging(value);
                    this.SendPropertyChanging();
                    this._student_id = value;
                    this.SendPropertyChanged("student_id");
                    this.Onstudent_idChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_call_number", DbType = "NVarChar(255)")]
        public string call_number
        {
            get
            {
                return this._call_number;
            }
            set
            {
                if ((this._call_number != value))
                {
                    this.Oncall_numberChanging(value);
                    this.SendPropertyChanging();
                    this._call_number = value;
                    this.SendPropertyChanged("call_number");
                    this.Oncall_numberChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_created_at", DbType = "DateTime")]
        public System.Nullable<System.DateTime> created_at
        {
            get
            {
                return this._created_at;
            }
            set
            {
                if ((this._created_at != value))
                {
                    this.Oncreated_atChanging(value);
                    this.SendPropertyChanging();
                    this._created_at = value;
                    this.SendPropertyChanged("created_at");
                    this.Oncreated_atChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_updated_at", DbType = "DateTime")]
        public System.Nullable<System.DateTime> updated_at
        {
            get
            {
                return this._updated_at;
            }
            set
            {
                if ((this._updated_at != value))
                {
                    this.Onupdated_atChanging(value);
                    this.SendPropertyChanging();
                    this._updated_at = value;
                    this.SendPropertyChanged("updated_at");
                    this.Onupdated_atChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [Table(Name = "ats_prod.sections")]
    public partial class section : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _id;

        private string _call_number;

        private string _course_name;

        private string _inst_id;

        private string _room;

        private string _days;

        private System.Nullable<System.TimeSpan> _start;

        private System.Nullable<System.TimeSpan> _end;

        private System.Nullable<System.DateTime> _created_at;

        private System.Nullable<System.DateTime> _updated_at;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnidChanging(int value);
        partial void OnidChanged();
        partial void Oncall_numberChanging(string value);
        partial void Oncall_numberChanged();
        partial void Oncourse_nameChanging(string value);
        partial void Oncourse_nameChanged();
        partial void Oninst_idChanging(string value);
        partial void Oninst_idChanged();
        partial void OnroomChanging(string value);
        partial void OnroomChanged();
        partial void OndaysChanging(string value);
        partial void OndaysChanged();
        partial void OnstartChanging(System.Nullable<System.TimeSpan> value);
        partial void OnstartChanged();
        partial void OnendChanging(System.Nullable<System.TimeSpan> value);
        partial void OnendChanged();
        partial void Oncreated_atChanging(System.Nullable<System.DateTime> value);
        partial void Oncreated_atChanged();
        partial void Onupdated_atChanging(System.Nullable<System.DateTime> value);
        partial void Onupdated_atChanged();
        #endregion

        public section()
        {
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    this.OnidChanging(value);
                    this.SendPropertyChanging();
                    this._id = value;
                    this.SendPropertyChanged("id");
                    this.OnidChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_call_number", DbType = "NVarChar(255)")]
        public string call_number
        {
            get
            {
                return this._call_number;
            }
            set
            {
                if ((this._call_number != value))
                {
                    this.Oncall_numberChanging(value);
                    this.SendPropertyChanging();
                    this._call_number = value;
                    this.SendPropertyChanged("call_number");
                    this.Oncall_numberChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_course_name", DbType = "NVarChar(255)")]
        public string course_name
        {
            get
            {
                return this._course_name;
            }
            set
            {
                if ((this._course_name != value))
                {
                    this.Oncourse_nameChanging(value);
                    this.SendPropertyChanging();
                    this._course_name = value;
                    this.SendPropertyChanged("course_name");
                    this.Oncourse_nameChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_inst_id", DbType = "NVarChar(255)")]
        public string inst_id
        {
            get
            {
                return this._inst_id;
            }
            set
            {
                if ((this._inst_id != value))
                {
                    this.Oninst_idChanging(value);
                    this.SendPropertyChanging();
                    this._inst_id = value;
                    this.SendPropertyChanged("inst_id");
                    this.Oninst_idChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_room", DbType = "NVarChar(255)")]
        public string room
        {
            get
            {
                return this._room;
            }
            set
            {
                if ((this._room != value))
                {
                    this.OnroomChanging(value);
                    this.SendPropertyChanging();
                    this._room = value;
                    this.SendPropertyChanged("room");
                    this.OnroomChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_days", DbType = "NVarChar(255)")]
        public string days
        {
            get
            {
                return this._days;
            }
            set
            {
                if ((this._days != value))
                {
                    this.OndaysChanging(value);
                    this.SendPropertyChanging();
                    this._days = value;
                    this.SendPropertyChanged("days");
                    this.OndaysChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_start", DbType = "Time")]
        public System.Nullable<System.TimeSpan> start
        {
            get
            {
                return this._start;
            }
            set
            {
                if ((this._start != value))
                {
                    this.OnstartChanging(value);
                    this.SendPropertyChanging();
                    this._start = value;
                    this.SendPropertyChanged("start");
                    this.OnstartChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_end", DbType = "Time ")]
        public System.Nullable<System.TimeSpan> end
        {
            get
            {
                return this._end;
            }
            set
            {
                if ((this._end != value))
                {
                    this.OnendChanging(value);
                    this.SendPropertyChanging();
                    this._end = value;
                    this.SendPropertyChanged("end");
                    this.OnendChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_created_at", DbType = "DateTime")]
        public System.Nullable<System.DateTime> created_at
        {
            get
            {
                return this._created_at;
            }
            set
            {
                if ((this._created_at != value))
                {
                    this.Oncreated_atChanging(value);
                    this.SendPropertyChanging();
                    this._created_at = value;
                    this.SendPropertyChanged("created_at");
                    this.Oncreated_atChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_updated_at", DbType = "DateTime")]
        public System.Nullable<System.DateTime> updated_at
        {
            get
            {
                return this._updated_at;
            }
            set
            {
                if ((this._updated_at != value))
                {
                    this.Onupdated_atChanging(value);
                    this.SendPropertyChanging();
                    this._updated_at = value;
                    this.SendPropertyChanged("updated_at");
                    this.Onupdated_atChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [Table(Name = "ats_prod.students")]
    public partial class student : INotifyPropertyChanging, INotifyPropertyChanged
    {

        private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);

        private int _id;

        private string _student_id;

        private string _s_number;

        private string _name;

        private System.Nullable<System.DateTime> _created_at;

        private System.Nullable<System.DateTime> _updated_at;

        #region Extensibility Method Definitions
        partial void OnLoaded();
        partial void OnValidate(System.Data.Linq.ChangeAction action);
        partial void OnCreated();
        partial void OnidChanging(int value);
        partial void OnidChanged();
        partial void Onstudent_idChanging(string value);
        partial void Onstudent_idChanged();
        partial void Ons_numberChanging(string value);
        partial void Ons_numberChanged();
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        partial void Oncreated_atChanging(System.Nullable<System.DateTime> value);
        partial void Oncreated_atChanged();
        partial void Onupdated_atChanging(System.Nullable<System.DateTime> value);
        partial void Onupdated_atChanged();
        #endregion

        public student()
        {
            OnCreated();
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_id", AutoSync = AutoSync.OnInsert, DbType = "Int NOT NULL IDENTITY", IsPrimaryKey = true, IsDbGenerated = true)]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                if ((this._id != value))
                {
                    this.OnidChanging(value);
                    this.SendPropertyChanging();
                    this._id = value;
                    this.SendPropertyChanged("id");
                    this.OnidChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_student_id", DbType = "NVarChar(255)")]
        public string student_id
        {
            get
            {
                return this._student_id;
            }
            set
            {
                if ((this._student_id != value))
                {
                    this.Onstudent_idChanging(value);
                    this.SendPropertyChanging();
                    this._student_id = value;
                    this.SendPropertyChanged("student_id");
                    this.Onstudent_idChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_s_number", DbType = "NVarChar(255)")]
        public string s_number
        {
            get
            {
                return this._s_number;
            }
            set
            {
                if ((this._s_number != value))
                {
                    this.Ons_numberChanging(value);
                    this.SendPropertyChanging();
                    this._s_number = value;
                    this.SendPropertyChanged("s_number");
                    this.Ons_numberChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_name", DbType = "NVarChar(255)")]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                if ((this._name != value))
                {
                    this.OnnameChanging(value);
                    this.SendPropertyChanging();
                    this._name = value;
                    this.SendPropertyChanged("name");
                    this.OnnameChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_created_at", DbType = "DateTime")]
        public System.Nullable<System.DateTime> created_at
        {
            get
            {
                return this._created_at;
            }
            set
            {
                if ((this._created_at != value))
                {
                    this.Oncreated_atChanging(value);
                    this.SendPropertyChanging();
                    this._created_at = value;
                    this.SendPropertyChanged("created_at");
                    this.Oncreated_atChanged();
                }
            }
        }

        [global::System.Data.Linq.Mapping.ColumnAttribute(Storage = "_updated_at", DbType = "DateTime")]
        public System.Nullable<System.DateTime> updated_at
        {
            get
            {
                return this._updated_at;
            }
            set
            {
                if ((this._updated_at != value))
                {
                    this.Onupdated_atChanging(value);
                    this.SendPropertyChanging();
                    this._updated_at = value;
                    this.SendPropertyChanged("updated_at");
                    this.Onupdated_atChanged();
                }
            }
        }

        public event PropertyChangingEventHandler PropertyChanging;

        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void SendPropertyChanging()
        {
            if ((this.PropertyChanging != null))
            {
                this.PropertyChanging(this, emptyChangingEventArgs);
            }
        }

        protected virtual void SendPropertyChanged(String propertyName)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    }
}
#pragma warning restore 1591
